#include "../print_x86_64.h"
#include "../print_x86_64_unofficial.h"
#include <stdio.h>

int main()
{
#ifdef OSX
puts(
"	.globl	_debug_write            ## -- Begin function debug_write\n" 
"_debug_write:                           ## @debug_write\n" 
"	pushq	%rbp\n" 
"	movq	%rsp, %rbp\n" 
"	pushq	%r15\n" 
"	pushq	%r14\n" 
"	pushq	%r13\n" 
"	pushq	%r12\n" 
"	pushq	%rbx\n" 
"	subq	$216, %rsp\n" 
"	movq	%rdi, %rbx\n" 
"	testb	%al, %al\n" 
"	movq	%rsi, -248(%rbp)\n" 
"	movq	%rdx, -240(%rbp)\n" 
"	movq	%rcx, -232(%rbp)\n" 
"	movq	%r8, -224(%rbp)\n" 
"	movq	%r9, -216(%rbp)\n" 
"	je	LBB0_2\n" 
"	movaps	%xmm0, -208(%rbp)\n" 
"	movaps	%xmm1, -192(%rbp)\n" 
"	movaps	%xmm2, -176(%rbp)\n" 
"	movaps	%xmm3, -160(%rbp)\n" 
"	movaps	%xmm4, -144(%rbp)\n" 
"	movaps	%xmm5, -128(%rbp)\n" 
"	movaps	%xmm6, -112(%rbp)\n" 
"	movaps	%xmm7, -96(%rbp)\n" 
"LBB0_2:\n" 
"	movq	___stack_chk_guard@GOTPCREL(%rip), %rax\n" 
"	movq	(%rax), %rax\n" 
"	movq	%rax, -48(%rbp)\n" 
"	leaq	-256(%rbp), %r15\n" 
"	movq	%r15, -64(%rbp)\n" 
"	leaq	16(%rbp), %r12\n" 
"	movq	%r12, -72(%rbp)\n" 
"	movabsq	$206158430216, %r13     ## imm = 0x3000000008\n" 
"	movq	%r13, -80(%rbp)\n" 
"	movq	___stderrp@GOTPCREL(%rip), %rax\n" 
"	movq	(%rax), %rdi\n" 
"	leaq	-80(%rbp), %r14\n" 
"	movq	%rbx, %rsi\n" 
"	movq	%r14, %rdx\n" 
"	callq	_vfprintf\n" 
"	movq	%r15, -64(%rbp)\n" 
"	movq	%r12, -72(%rbp)\n" 
"	movq	%r13, -80(%rbp)\n" 
"	movq	%rbx, %rdi\n" 
"	movq	%r14, %rsi\n" 
"	callq	_vprintf\n" 
"	movq	___stack_chk_guard@GOTPCREL(%rip), %rax\n" 
"	movq	(%rax), %rax\n" 
"	cmpq	-48(%rbp), %rax\n" 
"	jne	LBB0_4\n" 
"	addq	$216, %rsp\n" 
"	popq	%rbx\n" 
"	popq	%r12\n" 
"	popq	%r13\n" 
"	popq	%r14\n" 
"	popq	%r15\n" 
"	popq	%rbp\n" 
"	retq\n" 
"LBB0_4:\n" 
"	callq	___stack_chk_fail\n" );
#endif

#ifdef LINUX
puts(
"	.globl	debug_write\n" 
"debug_write:\n" 
"	pushq	%rbp\n" 
"	movq	%rsp, %rbp\n" 
"	pushq	%rbx\n" 
"	movq	%rdi, %rbx\n" 
"	subq	$216, %rsp\n" 
"	testb	%al, %al\n" 
"	movq	%rsi, -184(%rbp)\n" 
"	movq	%rdx, -176(%rbp)\n" 
"	movq	%rcx, -168(%rbp)\n" 
"	movq	%r8, -160(%rbp)\n" 
"	movq	%r9, -152(%rbp)\n" 
"	je	.L2\n" 
"	movaps	%xmm0, -144(%rbp)\n" 
"	movaps	%xmm1, -128(%rbp)\n" 
"	movaps	%xmm2, -112(%rbp)\n" 
"	movaps	%xmm3, -96(%rbp)\n" 
"	movaps	%xmm4, -80(%rbp)\n" 
"	movaps	%xmm5, -64(%rbp)\n" 
"	movaps	%xmm6, -48(%rbp)\n" 
"	movaps	%xmm7, -32(%rbp)\n" 
".L2:\n" 
"	movq	%fs:40, %rax\n" 
"	movq	%rax, 24(%rsp)\n" 
"	xorl	%eax, %eax\n" 
"	leaq	240(%rsp), %rax\n" 
"	movq	%rsp, %rbp\n" 
"	movq	%rbx, %rdx\n" 
"	movq	%rbp, %rcx\n" 
"	movl	$1, %esi\n" 
"	movq	stderr(%rip), %rdi\n" 
"	movq	%rax, 8(%rsp)\n" 
"	leaq	32(%rsp), %rax\n" 
"	movl	$8, (%rsp)\n" 
"	movl	$48, 4(%rsp)\n" 
"	movq	%rax, 16(%rsp)\n" 
"	call	__vfprintf_chk@PLT\n" 
"	leaq	240(%rsp), %rax\n" 
"	movq	stdout(%rip), %rdi\n" 
"	movq	%rbp, %rcx\n" 
"	movq	%rbx, %rdx\n" 
"	movl	$1, %esi\n" 
"	movl	$8, (%rsp)\n" 
"	movq	%rax, 8(%rsp)\n" 
"	leaq	32(%rsp), %rax\n" 
"	movl	$48, 4(%rsp)\n" 
"	movq	%rax, 16(%rsp)\n" 
"	call	__vfprintf_chk@PLT\n" 
"	movq	24(%rsp), %rax\n" 
"	xorq	%fs:40, %rax\n" 
"	jne	.L6\n" 
"	addq	$216, %rsp\n" 
"	popq	%rbx\n" 
"	popq	%rbp\n" 
"	ret\n" 
".L6:\n" 
"	call	__stack_chk_fail@PLT\n" 
);
#endif

}
