void print_prologue(int alloc_size);
void push_int(int num);
void print_epilogue(int alloc_size);
void op_ints(const char* str);
void compare_ints(const char* str);
void mul_ints(void);
void div_ints(void);
void rem_ints(void);
void shift_ints(const char* str);
void unary_not(void);
void unary_bitnot(void);
void push_from_local(int offset);
void write_to_local(int offset);
